# Generated by Django 3.2.4 on 2022-01-08 23:32

from django.db import migrations, models
import shared.models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0005_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=shared.models.recipe_image_file_path),
        ),
    ]
